### ISSUE TITLE
求助：远程下载生成好的文件，360落地报毒隔离，但是运行&上报又查无风险。有办法解决吗？

### ISSUE THREAD

**Issue by furuanruan** [yutianqaq/AVEvasionCraftOnline#13]
![Uploading 未命名图片.png…]()

**Comment by yutianqaq** [comment]
加图标 假签名等等

**Comment by yutianqaq** [comment]
https://xz.aliyun.com/t/13411?time__1311=mqmxnDBQqDq7wq05d4%2BxCuwCxu7faQQY4D#toc-6:~:text=%E4%BB%93%E5%BA%93%E4%BD%9C%E8%80%85%E4%BB%98%E5%87%BA%E3%80%82-,%E7%BB%93%E8%AF%AD,-%E6%9C%80%E5%90%8E%E7%9A%84%E5%B0%8F
