### ISSUE TITLE
选择内嵌模式，测试不上线！！！

### ISSUE THREAD

**Issue by AhrendsSchmidt** [yutianqaq/AVEvasionCraftOnline#15]
进程在，程序也没有退出，但是没有外联请求，模板编译的有问题？
![image](https://github.com/yutianqaq/AVEvasionCraftOnline/assets/33677393/0aacedad-b533-4081-a213-ec0adc81dcdd)
使用这个版本测试的
![image](https://github.com/yutianqaq/AVEvasionCraftOnline/assets/33677393/4ef5eae9-e767-415c-9bda-e7eadd05d937)
服务器端编译正常，也没有报错
![image](https://github.com/yutianqaq/AVEvasionCraftOnline/assets/33677393/f328c029-fecb-4a86-82c6-90ce46d07954)

**Comment by yutianqaq** [comment]
周末再看看

**Comment by yutianqaq** [comment]
换一种加载方式吧，这种不能用
