### ISSUE TITLE
go_CertEnumSystemStore模板无法正常编译和一行代码似乎存在错误

### ISSUE THREAD

**Issue by nu11b1ade** [yutianqaq/AVEvasionCraftOnline#17]
### go_CertEnumSystemStore模板无法正常编译
环境：新安装的kali2024.1，环境应该和师傅的一致
使用go_CertEnumSystemStore模板时无法正常编译，提示缺少mod文件，报错截图如下：
![图片](https://github.com/yutianqaq/AVEvasionCraftOnline/assets/168897292/66075fb1-c5d2-4437-9528-944eed7f08b0)

去看了临时编译目录下确实没有mod文件，而GO111MODULE默认是空值（和on等价），是强制从mod文件获取依赖包，所以报错缺少mod文件。然后我改为auto或者off后又报错缺少依赖包`golang.org/x/sys/windows` ，报错截图如下：
![图片](https://github.com/yutianqaq/AVEvasionCraftOnline/assets/168897292/d1864ff6-45b1-4485-99cc-fb3a72dbf7b4)

似乎是依赖包的问题，到临时编译目录下手动get下依赖包然后手动编译是可以的，但就达不到平台自动化的目的了，麻烦师傅看下是什么情况。
### 一行代码似乎存在错误
`\AVEvasionCraftOnline-Backend\src\main\java\com\yutian4060\avevasioncraftonline\service\impl\CompileServiceImpl.java` 中的205行代码`if (Files.exists(goSumFilePath)) {` ，根据上下文判断应该为`if (Files.exists(goModFilePath)) {` 。

**Comment by nu11b1ade** [comment]
已解决， go_CertEnumSystemStore模板目录中的mod文件没有依赖包内容，在模板目录下执行`go mod tidy` ，更新mod文件的依赖内容即可。
另外，go_CertEnumSystemStore模板目录中的go源文件均少了main包的声明`package main` 。

**Comment by yutianqaq** [comment]
已更新 🫡
