### ISSUE TITLE
C和GO版本编译没问题，但是NIM版本的编译报错

### ISSUE THREAD

**Issue by xufengnian** [yutianqaq/AVEvasionCraftOnline#2]
CentOS 7 x64，已经安装了NIM，然后报错
![image](https://github.com/yutianqaq/AVEvasionCraftOnline/assets/15324125/9261fa00-edbf-4c70-97ca-5b458892818f)
![image](https://github.com/yutianqaq/AVEvasionCraftOnline/assets/15324125/9874a65f-3eb5-4918-a845-2ba7d4a6cc00)

然后C版本的c_VirtualAlloc.c文件路径有点问题，需要再创建一个EMBEDDED目录，把c_VirtualAlloc.c放进去，否则会报错找不到文件

**Comment by yutianqaq** [comment]
安装 winim了吗

**Comment by xufengnian** [comment]
> 安装 winim了吗

都按照安装文档的步骤，已经安装过了的
![image](https://github.com/yutianqaq/AVEvasionCraftOnline/assets/15324125/53623472-aaf3-443c-a5ac-5403d9c2481b)

**Comment by xufengnian** [comment]
好的，我回头试下kali，然后2024.02.02实测C版本的exe，火绒可以杀，Go版本的目前还是免杀状态
