### ISSUE TITLE
Request failed with status code 500

### ISSUE THREAD

**Issue by 1764549853** [yutianqaq/AVEvasionCraftOnline#25]
都用不了啊

**Comment by 1764549853** [comment]
然后我试了详细教程里的安装依赖 装了go依赖 然后是超时 15000

**Comment by yutianqaq** [comment]
1、看后台报错
2、golang 下载包需要梯子，或者搜索golang 国内代理

**Comment by 1764549853** [comment]
你好，我刚看到你的邮件，我想问一下，我安装完了go依赖，然后成功生成了，但是我却无法运行，我可以点击exe，但是exe却没有在进程中，免杀是没问题的，但cobaltstrike却没有反应，我可以直接删除exe，因为他没有进程



发自我的iPhone


------------------ Original ------------------
From: yutianqaq ***@***.***&gt;
Date: Wed,Aug 7,2024 10:10 PM
To: yutianqaq/AVEvasionCraftOnline ***@***.***&gt;
Cc: 1764549853 ***@***.***&gt;, State change ***@***.***&gt;
Subject: Re: [yutianqaq/AVEvasionCraftOnline] Request failed with status code500 (Issue #25)

**Comment by yutianqaq** [comment]
可能是go版本太高，一些运行环境不支持，试试1.8之类的
也有可能编译出来的不是exe pe-bear 看一看
