### ISSUE TITLE
password

### ISSUE THREAD

**Issue by sec13b** [yutianqaq/AVEvasionCraftOnline#3]
can i have the password , please.
thank you

**Comment by yutianqaq** [comment]
The password is  公众号赛博雨天
Unzip using winrar or 7z
The password for the zip generated by the platform is yutian

**Comment by yutianqaq** [comment]
https://drive.google.com/file/d/1jRZxvRPyC5kaLvo3eDz5Q3ktdvAOQ6dn/view
